### ISSUE TITLE
Translation to Spanish script

### ISSUE THREAD

**Issue by picunder** [DmitrySidorow/GrafanaTranslator#14]
Hi Dimitry ... I used your script as base for spanish translator. Please feel free to review and use the atached script for translating to spanish. 

Great work and thanks! . I´m happy to contribute to your project.

Regards

Francisco Picatto

Argentina.

[spanish.zip](https://github.com/DmitrySidorow/GrafanaTranslator/files/6266650/spanish.zip)

**Comment by DmitrySidorow** [comment]
Thank you! Done https://github.com/DmitrySidorow/GrafanaTranslator/commit/497fe0e026a9afadb1c11eab0961dc2a6353016b
