### ISSUE TITLE
Time zone combobox translation should be added

### ISSUE THREAD

**Issue by izzetkalic** [DmitrySidorow/GrafanaTranslator#2]
I couldn't see the translation of time zone combobox placeholder. It would be nice if you can add.

![image](https://user-images.githubusercontent.com/8526134/104297296-c3846b00-54d3-11eb-9dad-24837949efc0.png)

**Comment by DmitrySidorow** [comment]
Done  https://github.com/DmitrySidorow/GrafanaTranslator/commit/fbccf4216381dc7de965fc0c96d3e27abc6d493b
