### ISSUE TITLE
Прошу сделайте для Win10

### ISSUE THREAD

**Issue by baur** [DmitrySidorow/GrafanaTranslator#9]
Добрый день,
Прошу, сделайте для Win10 (Windows Server 2016) тоже, или подскажите как это делается вручную. Установлен через zip а не msi

**Comment by baur** [comment]
[нашел аналог sed](http://gnuwin32.sourceforge.net/packages/sed.htm)

Спасибо вам за работу!

**Comment by baur** [comment]
Запустил под Win10, пишет:
```
>sed -i 's/"Last 5 minutes"/"Последние 5 минут"/g' app*.js*
sed: -e выражение #1, символ 1: неизвестная команда: `''
...
```

**Comment by DmitrySidorow** [comment]
Привет!
Для перевода лучше всего клонировать нужную ветку grafana, открыть в удобном редакторе (я использую WebStorm), после перевода собрать по инструкции https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md
Собирать удобнее на linux (в моем случае ubuntu). После папку build и файл grafana-server переносишь в винду
Если будут вопросы, пиши)
